version: "3.9"
services:
    db:
        image: postgres:latest
        container_name: db
        environment:
            - POSTGRES_DB=residue_monitoring_system
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=12345
        expose:
            - 5432

    backend:
        image: backend
        container_name: backend
        build:
            context: ./backend
        ports:
            - "8080:80"
        environment:
          - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/residue_monitoring_system
        depends_on:
            - db
    frontend:
        image: frontend
        container_name: frontend
        build:
            context: ./frontend
        ports:
            - "4200:80"
        depends_on:
            - backend
